### ISSUE TITLE
iothub_hostname in iotedge_config.yaml not used

### ISSUE THREAD

**Issue by apulliam** [Azure-Samples/iotedge_config_cli#14]
I was wondering why the iotedge_config tool would require iothub_hostname and iothub_name, since the latter is a component of the first.  I'm new to Rust, but upon looking at the Rust source, it appears iothub_hostname is not used.

**Comment by jlian** [comment]
Another reason is that, in Azure US Gov for example, the IoT Hub hostname is different (*.azure-devices.us), so it's best to ask the user. 

EDIT: though in that case the tool could just use `az iot hub show` and find the hostname returned. Hmm
